server:
  port: ${LAVALINK_PORT:2333}

lavalink:
  server:
    password: ${LAVALINK_PASSWORD:youshallnotpass}
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
    bufferDurationMs: 400
    resume: true
    resumeTimeout: 60

metrics:
  prometheus:
    enabled: false

logging:
  file:
    max-history: 30
